{{- if ge (int .Values.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api-pdb
  labels:
    app.kubernetes.io/name: fluxa
    app.kubernetes.io/component: api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fluxa
      app.kubernetes.io/component: api
{{- end }}
---
{{- if ge (int .Values.worker.replicaCount) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker-pdb
  labels:
    app.kubernetes.io/name: fluxa
    app.kubernetes.io/component: worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fluxa
      app.kubernetes.io/component: worker
{{- end }}
