apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-api-sa
  labels:
    app.kubernetes.io/name: fluxa
    app.kubernetes.io/component: api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-worker-sa
  labels:
    app.kubernetes.io/name: fluxa
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
