import React from 'react';
import { useNavigate } from 'react-router-dom';
import * as Icons from 'lucide-react';
import { useToast } from '../shared/components/Toast';
import { authenticatedFetch } from '../shared/api/authenticatedFetch';

interface WorkflowItem {
  id: string;
  name: string;
  description: string;
  status: string;
  current_version: string;
}

export const WorkflowsPage: React.FC = () => {
  const [workflows, setWorkflows] = React.useState<WorkflowItem[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [isCreateOpen, setIsCreateOpen] = React.useState(false);
  const [creating, setCreating] = React.useState(false);

  // Form states
  const [newName, setNewName] = React.useState('');
  const [newDesc, setNewDesc] = React.useState('');

  const navigate = useNavigate();
  const { showToast } = useToast();

  const fetchWorkflows = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await authenticatedFetch('/api/v1/workflows/');
      if (!res.ok) throw new Error('Failed to fetch workflows list from server');
      const data = await res.json();
      setWorkflows(data || []);
    } catch (err: any) {
      setError(err.message || 'Unable to connect to workflows service.');
      showToast(err.message || 'Error loading workflows', 'error');
    } finally {
      setLoading(false);
    }
  }, [showToast]);

  React.useEffect(() => {
    fetchWorkflows();
  }, [fetchWorkflows]);

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newName.trim()) {
      showToast('Please enter a workflow name.', 'warning');
      return;
    }

    setCreating(true);
    try {
      const res = await authenticatedFetch('/api/v1/workflows/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: newName.trim(),
          description: newDesc.trim(),
          nodes: [],
          edges: [],
          variables: {},
        }),
      });

      if (!res.ok) {
        let errMsg = 'Failed to create workflow';
        try {
          const b = await res.json();
          errMsg = b.message || b.detail || errMsg;
        } catch {}
        throw new Error(errMsg);
      }
      const data = await res.json();
      showToast(`Workflow "${data.name}" created successfully.`, 'success');
      
      setIsCreateOpen(false);
      setNewName('');
      setNewDesc('');
      
      // Navigate to builder
      navigate(`/workflows/${data.id}`);
    } catch (err: any) {
      showToast(err.message || 'Failed to create workflow', 'error');
    } finally {
      setCreating(false);
    }
  };

  const handleDelete = async (id: string, name: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!window.confirm(`Are you sure you want to delete "${name}"?`)) return;

    try {
      const { workflowRepositoryInstance } = await import('../features/builder/infrastructure/api/workflowRepository');
      await workflowRepositoryInstance.delete(id);
      showToast(`Workflow "${name}" deleted successfully.`, 'success');
      fetchWorkflows();
    } catch (err: any) {
      showToast(err.message || 'Failed to delete workflow', 'error');
    }
  };


  const handleDuplicate = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      // 1. Fetch source workflow details
      const detailRes = await authenticatedFetch(`/api/v1/workflows/${id}`);
      if (!detailRes.ok) throw new Error('Failed to fetch original workflow details');
      const src = await detailRes.json();

      // 2. Build creation payload (new identity generated by backend)
      const res = await authenticatedFetch('/api/v1/workflows/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: `Copy of ${src.name}`,
          description: src.description || '',
          nodes: src.nodes || [],
          edges: src.edges || [],
          variables: src.variables || {},
        }),
      });

      if (!res.ok) throw new Error('Failed to duplicate workflow');
      const data = await res.json();
      showToast(`Workflow duplicated successfully as "${data.name}".`, 'success');
      
      navigate(`/workflows/${data.id}`);
    } catch (err: any) {
      showToast(err.message || 'Failed to duplicate workflow', 'error');
    }
  };

  return (
    <div className="flex-1 h-full p-6 text-left bg-background overflow-y-auto">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <Icons.Workflow className="text-primary" size={20} />
          <h2 className="font-bold text-lg text-foreground">Workflows</h2>
        </div>
        <button
          onClick={() => setIsCreateOpen(true)}
          className="flex items-center gap-2 px-4 py-2 bg-primary hover:bg-primary/95 text-white text-xs font-bold rounded-xl shadow-lg shadow-primary/20 transition-all cursor-pointer"
        >
          <Icons.Plus size={14} />
          Create Workflow
        </button>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-16 gap-3 text-muted-foreground">
          <Icons.Loader2 className="animate-spin text-primary" size={24} />
          <span className="text-xs font-medium">Loading workflows...</span>
        </div>
      ) : error ? (
        <div className="border border-destructive/30 bg-destructive/5 rounded-2xl p-8 text-center flex flex-col items-center gap-3">
          <Icons.AlertCircle className="text-destructive" size={32} />
          <div>
            <h3 className="font-bold text-sm text-foreground mb-1">Failed to load workflows</h3>
            <p className="text-xs text-muted-foreground">{error}</p>
          </div>
          <button
            onClick={fetchWorkflows}
            className="flex items-center gap-2 px-4 py-2 bg-primary hover:bg-primary/90 text-white text-xs font-bold rounded-xl transition-all cursor-pointer shadow-md"
          >
            <Icons.RotateCw size={13} />
            Retry Request
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {workflows.map((wf) => (
            <div
              key={wf.id}
              onClick={() => navigate(`/workflows/${wf.id}`)}
              className="border border-border rounded-2xl bg-card p-5 shadow-md flex flex-col justify-between transition-all hover:border-primary/40 hover:shadow-xl cursor-pointer group relative overflow-hidden"
            >
              <div>
                <div className="flex items-center justify-between gap-2 mb-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20">
                    {wf.status || 'Draft'}
                  </span>
                  <span className="text-[10px] text-muted-foreground font-mono">{wf.current_version}</span>
                </div>
                <h4 className="font-bold text-sm text-foreground group-hover:text-primary transition-colors line-clamp-1">{wf.name}</h4>
                <p className="text-xs text-muted-foreground mt-1 line-clamp-2 min-h-[32px]">{wf.description || 'No description provided.'}</p>
              </div>

              <div className="flex items-center justify-end gap-1.5 mt-4 pt-3 border-t border-border/50 shrink-0">
                <button
                  onClick={(e) => handleDuplicate(wf.id, e)}
                  className="p-1.5 rounded-lg hover:bg-secondary text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                  title="Duplicate Workflow"
                >
                  <Icons.Copy size={13} />
                </button>
                <button
                  onClick={(e) => handleDelete(wf.id, wf.name, e)}
                  className="p-1.5 rounded-lg hover:bg-destructive/20 text-muted-foreground hover:text-destructive transition-colors cursor-pointer"
                  title="Delete Workflow"
                >
                  <Icons.Trash2 size={13} />
                </button>
              </div>
            </div>
          ))}

          {workflows.length === 0 && (
            <div className="col-span-full border border-dashed border-border rounded-2xl p-12 text-center flex flex-col items-center gap-2">
              <Icons.Workflow className="text-muted-foreground/40" size={36} />
              <div className="font-bold text-sm text-foreground">No workflows found</div>
              <p className="text-xs text-muted-foreground max-w-sm">
                There are no workflows in this workspace yet. Click "Create Workflow" above to get started.
              </p>
            </div>
          )}
        </div>
      )}

      {/* Create Workflow Modal */}
      {isCreateOpen && (
        <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setIsCreateOpen(false)}>
          <div className="w-full max-w-md bg-card border border-border rounded-2xl shadow-2xl overflow-hidden text-left" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between p-4 border-b border-border">
              <h3 className="font-bold text-sm text-foreground flex items-center gap-2">
                <Icons.PlusSquare size={16} className="text-primary" />
                Create New Workflow
              </h3>
              <button onClick={() => setIsCreateOpen(false)} className="p-1 rounded hover:bg-secondary text-muted-foreground hover:text-foreground">
                <Icons.X size={15} />
              </button>
            </div>
            <form onSubmit={handleCreate} className="p-4 space-y-4">
              <div>
                <label className="text-xs font-semibold text-foreground block mb-1">Workflow Name</label>
                <input
                  type="text"
                  placeholder="e.g. Sales Ingestion & Lead Triage"
                  className="w-full bg-background border border-border rounded-xl px-3 py-2 text-xs text-foreground focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary"
                  value={newName}
                  onChange={(e) => setNewName(e.target.value)}
                  disabled={creating}
                  required
                />
              </div>
              <div>
                <label className="text-xs font-semibold text-foreground block mb-1">Description (Optional)</label>
                <textarea
                  placeholder="Describe what this workflow automation does..."
                  className="w-full bg-background border border-border rounded-xl px-3 py-2 text-xs text-foreground focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary min-h-[80px]"
                  value={newDesc}
                  onChange={(e) => setNewDesc(e.target.value)}
                  disabled={creating}
                />
              </div>
              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setIsCreateOpen(false)}
                  disabled={creating}
                  className="px-4 py-2 border border-border rounded-xl text-xs text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={creating}
                  className="px-4 py-2 bg-primary hover:bg-primary/95 text-white text-xs font-bold rounded-xl shadow-md transition-all flex items-center gap-1.5 cursor-pointer"
                >
                  {creating && <Icons.Loader className="animate-spin" size={13} />}
                  <span>Create Workflow</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
export default WorkflowsPage;
